const fs=require('fs'),path=require('path'),matter=require('gray-matter');const MarkdownIt=require('markdown-it');const anchor=require('markdown-it-anchor');const footnote=require('markdown-it-footnote');const tasks=require('markdown-it-task-lists');const hl=require('highlight.js');const katex=require('katex');
const root=path.join(__dirname,'..'),out=path.join(root,'dist');
const md=new MarkdownIt({html:true,linkify:true,highlight:(s,l)=>l&&hl.getLanguage(l)?`<pre class="hljs"><code>${hl.highlight(s,{language:l,ignoreIllegals:true}).value}</code></pre>`:`<pre><code>${md.utils.escapeHtml(s)}</code></pre>`}).use(anchor).use(footnote).use(tasks);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]));
function render(s){s=s.replace(/\$\$([\s\S]+?)\$\$/g,(_,x)=>`<div class="math">${katex.renderToString(x.trim(),{displayMode:true,throwOnError:false})}</div>`);return s.replace(/(^|[^$])\$([^$\n]+?)\$/g,(_,a,x)=>a+katex.renderToString(x,{throwOnError:false}) )&&md.render(s)}
function layout(t,b){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/style.css"><link rel="manifest" href="/manifest.webmanifest"><title>${esc(t)} · 林间</title></head><body><header><div class="wrap"><a href="/" class="brand">林间<span>·</span></a><nav><a href="/">首页</a><a href="/admin/">写作</a></nav></div></header>${b}<footer class="wrap">© 2026 林间</footer></body></html>`}
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(path.join(out,'posts'),{recursive:true});fs.mkdirSync(path.join(out,'assets'),{recursive:true});fs.cpSync(path.join(root,'public'),out,{recursive:true});fs.cpSync(path.join(root,'admin'),path.join(out,'admin'),{recursive:true});
const dir=path.join(root,'content/posts');const posts=fs.readdirSync(dir).filter(x=>x.endsWith('.md')).map(file=>{const p=matter(fs.readFileSync(path.join(dir,file),'utf8'));return {p,data:{...p.data,slug:p.data.slug||file.slice(0,-3)}}}).sort((a,b)=>String(b.data.date).localeCompare(String(a.data.date)));
for(const x of posts){const d=x.data;fs.writeFileSync(path.join(out,'posts',d.slug+'.html'),layout(d.title,`<main class="wrap article"><div class="meta">${esc(d.date)} · ${esc(d.category||'随笔')}</div><h1>${esc(d.title)}</h1><p class="lead">${esc(d.description||'')}</p>${render(x.p.content)}</main>`))}
fs.writeFileSync(path.join(out,'index.html'),layout('首页',`<main class="wrap"><section class="hero"><small>PERSONAL BLOG</small><h1>记录想法，分享发现。</h1><p>Markdown 写作，手机发布，Cloudflare Pages 托管。</p></section>${posts.map(x=>`<article class="card"><div class="meta">${esc(x.data.date)} · ${esc(x.data.category||'随笔')}</div><h2><a href="/posts/${esc(x.data.slug)}.html">${esc(x.data.title)}</a></h2><p>${esc(x.data.description||'')}</p></article>`).join('')}</main>`));console.log(`Built ${posts.length} posts`);
